update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -131,8 +131,17 @@ jobs:
             if [ -z "$package" ] || [ -z "$pkgbuild" ]; then
               continue
             fi
-            echo "==== Building package: $package ===="
+            echo "::group::==== Building package: $package ===="
+            echo "==== Building package: $package ====" >> $GITHUB_STEP_SUMMARY
             sudo -u builder bash ./buildscript.sh "${{ github.repository }}" "$GH_TOKEN" "$GITHUB_WORKSPACE" $build "$package" "$pkgbuild" "Auto update $package "
+            if [[ $? -eq 0 ]]; then
+              echo "$package completed SUCCESSFULLY"
+              echo "$package completed SUCCESSFULLY" >> $GITHUB_STEP_SUMMARY
+            else
+              echo "$package FAILED"
+              echo "$package FAILED" >> $GITHUB_STEP_SUMMARY
+            fi
+            echo "::endgroup::""
           done
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
